services:
    user.registration_completed_listener:
        class: UserBundle\EventListener\RegistrationListener
        arguments: ["@router"]
        tags:
            - name: kernel.event_listener
              event: fos_user.registration.success
              method: onRegistrationSuccess
